// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using gym.Models;

#nullable disable

namespace gym.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20250118184513_AddSubscriptionWorkout")]
    partial class AddSubscriptionWorkout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("C##SUNDOS")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubscriptionWorkout", b =>
                {
                    b.Property<decimal>("SubscriptionId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SUBSCRIPTION_ID");

                    b.Property<decimal>("WorkoutId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("WORKOUT_ID");

                    b.HasKey("SubscriptionId", "WorkoutId")
                        .HasName("SYS_C_SUBSCRIPTION_WORKOUT_PK");

                    b.HasIndex("WorkoutId");

                    b.ToTable("SUBSCRIPTION_WORKOUTS", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Aboutuspage", b =>
                {
                    b.Property<decimal>("AbModificationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("AB_MODIFICATIONID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("AbModificationid"));

                    b.Property<decimal>("Adminid")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ADMINID");

                    b.Property<string>("Headertitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("HEADERTITLE");

                    b.Property<string>("Image1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("IMAGE1");

                    b.Property<string>("Image2")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("IMAGE2");

                    b.Property<DateTime?>("Lastupdated")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("LASTUPDATED")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Paragraph1")
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("PARAGRAPH1");

                    b.Property<string>("Paragraph2")
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("PARAGRAPH2");

                    b.Property<string>("Paragraph3")
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("PARAGRAPH3");

                    b.HasKey("AbModificationid")
                        .HasName("SYS_C008526");

                    b.HasIndex("Adminid");

                    b.ToTable("ABOUTUSPAGE", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Contactusform", b =>
                {
                    b.Property<decimal>("Formid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("FORMID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Formid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Isreviewed")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ISREVIEWED")
                        .HasDefaultValueSql("'N' ")
                        .IsFixedLength();

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.Property<DateTime?>("Submittedat")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SUBMITTEDAT")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Formid")
                        .HasName("SYS_C008540");

                    b.ToTable("CONTACTUSFORM", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Contactuspage", b =>
                {
                    b.Property<decimal>("CModificationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("C_MODIFICATIONID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CModificationid"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<decimal>("Adminid")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ADMINID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime?>("Lastupdated")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("LASTUPDATED")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.HasKey("CModificationid")
                        .HasName("SYS_C008510");

                    b.HasIndex("Adminid");

                    b.ToTable("CONTACTUSPAGE", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Homepage", b =>
                {
                    b.Property<decimal>("HModificationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("H_MODIFICATIONID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("HModificationid"));

                    b.Property<decimal>("Adminid")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ADMINID");

                    b.Property<DateTime?>("Lastupdated")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("LASTUPDATED")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Sliderimage1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SLIDERIMAGE1");

                    b.Property<string>("Sliderimage2")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SLIDERIMAGE2");

                    b.Property<string>("Slidersubtitle1")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("SLIDERSUBTITLE1");

                    b.Property<string>("Slidersubtitle2")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("SLIDERSUBTITLE2");

                    b.Property<string>("Slidertitle1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SLIDERTITLE1");

                    b.Property<string>("Slidertitle2")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SLIDERTITLE2");

                    b.HasKey("HModificationid")
                        .HasName("SYS_C008532");

                    b.HasIndex("Adminid");

                    b.ToTable("HOMEPAGE", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.MembershipPlan", b =>
                {
                    b.Property<decimal>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("PLAN_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("PlanId"));

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("DETAILS");

                    b.Property<decimal>("PDuration")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("P_DURATION");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("PLAN_NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<int?>("WorkoutsNum")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PlanId")
                        .HasName("SYS_C008445");

                    b.ToTable("MEMBERSHIP_PLANS", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Report", b =>
                {
                    b.Property<decimal>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("REPORT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ReportId"));

                    b.Property<string>("PdfPath")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("PDF_PATH");

                    b.Property<string>("ReportTitle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("REPORT_TITLE");

                    b.Property<string>("ReportType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("REPORT_TYPE");

                    b.HasKey("ReportId")
                        .HasName("SYS_C008501");

                    b.ToTable("REPORTS", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Review", b =>
                {
                    b.Property<decimal>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("REVIEW_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ReviewId"));

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("FEEDBACK_TEXT");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("RATING");

                    b.Property<decimal>("SessionId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SESSION_ID");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SUBMITTED_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ReviewId")
                        .HasName("SYS_C008483");

                    b.HasIndex("SessionId");

                    b.ToTable("REVIEWS", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Rolee", b =>
                {
                    b.Property<decimal>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("RoleId")
                        .HasName("SYS_C008430");

                    b.HasIndex(new[] { "RoleName" }, "SYS_C008431")
                        .IsUnique();

                    b.ToTable("ROLEES", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Schedule", b =>
                {
                    b.Property<decimal>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SCHEDULE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ScheduleId"));

                    b.Property<string>("AvailableFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("AVAILABLE_FROM");

                    b.Property<string>("AvailableTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("AVAILABLE_TO");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("DAY_OF_WEEK");

                    b.Property<decimal>("SessionId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SESSION_ID");

                    b.Property<decimal>("TrainerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TRAINER_ID");

                    b.HasKey("ScheduleId")
                        .HasName("SYS_C008470");

                    b.HasIndex("SessionId");

                    b.HasIndex("TrainerId");

                    b.ToTable("SCHEDULES", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Session", b =>
                {
                    b.Property<decimal>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SESSION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("SessionId"));

                    b.Property<DateTime?>("CheckIn")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CHECK_IN");

                    b.Property<DateTime?>("CheckOut")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CHECK_OUT");

                    b.Property<DateTime>("EndTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("END_TIME");

                    b.Property<decimal>("MemberId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("START_TIME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TrainerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TRAINER_ID");

                    b.HasKey("SessionId")
                        .HasName("SYS_C008461");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("SESSIONS", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.StaticPage", b =>
                {
                    b.Property<decimal>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("PAGE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("PageId"));

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("LAST_UPDATED")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP\n");

                    b.Property<string>("PageContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("PAGE_CONTENT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("TITLE");

                    b.HasKey("PageId")
                        .HasName("SYS_C008493");

                    b.ToTable("STATIC_PAGES", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Subscription", b =>
                {
                    b.Property<decimal>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SUBSCRIPTION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("SubscriptionId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("END_DATE");

                    b.Property<string>("InvoicePath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("INVOICE_PATH");

                    b.Property<decimal>("PlanId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("PLAN_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("START_DATE");

                    b.Property<decimal>("UserId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("USER_ID");

                    b.HasKey("SubscriptionId")
                        .HasName("SYS_C008452");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("SUBSCRIPTIONS", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Testimonial", b =>
                {
                    b.Property<decimal>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TESTIMONIAL_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("TestimonialId"));

                    b.Property<string>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("IS_APPROVED")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SUBMITTED_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("T_CONTENT");

                    b.Property<decimal>("UserId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("USER_ID");

                    b.HasKey("TestimonialId")
                        .HasName("SYS_C008488");

                    b.HasIndex("UserId");

                    b.ToTable("TESTIMONIALS", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.UserLogin", b =>
                {
                    b.Property<decimal>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("LOGIN_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("LoginId"));

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("PASS");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("LoginId")
                        .HasName("SYS_C008497");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Username" }, "SYS_C008498")
                        .IsUnique();

                    b.ToTable("USER_LOGIN", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.Userr", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("USER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(600)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(600)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(250)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("PHONE");

                    b.Property<string>("PicPath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("PIC_PATH");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("ROLE_ID");

                    b.HasKey("UserId")
                        .HasName("SYS_C008437");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "SYS_C008438")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "SYS_C008439")
                        .IsUnique()
                        .HasFilter("\"PHONE\" IS NOT NULL");

                    b.ToTable("USERRS", "C##SUNDOS");
                });

            modelBuilder.Entity("gym.Models.WorkoutPlan", b =>
                {
                    b.Property<decimal>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("WORKOUT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("WorkoutId"));

                    b.Property<string>("Details")
                        .HasColumnType("CLOB")
                        .HasColumnName("DETAILS");

                    b.Property<string>("Goals")
                        .HasColumnType("CLOB")
                        .HasColumnName("GOALS");

                    b.Property<decimal>("MemberId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("MEMBER_ID");

                    b.Property<decimal>("TrainerId")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TRAINER_ID");

                    b.HasKey("WorkoutId")
                        .HasName("SYS_C008476");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("WORKOUT_PLANS", "C##SUNDOS");
                });

            modelBuilder.Entity("SubscriptionWorkout", b =>
                {
                    b.HasOne("gym.Models.Subscription", "Subscription")
                        .WithMany("SubscriptionWorkouts")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_SUBSCRIPTION_WORKOUT_SUBSCRIPTION");

                    b.HasOne("gym.Models.WorkoutPlan", "Workout")
                        .WithMany("SubscriptionWorkouts")
                        .HasForeignKey("WorkoutId")
                        .IsRequired()
                        .HasConstraintName("FK_SUBSCRIPTION_WORKOUT_WORKOUT");

                    b.Navigation("Subscription");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("gym.Models.Aboutuspage", b =>
                {
                    b.HasOne("gym.Models.Userr", "Admin")
                        .WithMany("Aboutuspages")
                        .HasForeignKey("Adminid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ABOUTUSPAGE_USER");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("gym.Models.Contactuspage", b =>
                {
                    b.HasOne("gym.Models.Userr", "Admin")
                        .WithMany("Contactuspages")
                        .HasForeignKey("Adminid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONTACTUSPAGE_USER");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("gym.Models.Homepage", b =>
                {
                    b.HasOne("gym.Models.Userr", "Admin")
                        .WithMany("Homepages")
                        .HasForeignKey("Adminid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HOMEPAGE_USER");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("gym.Models.Review", b =>
                {
                    b.HasOne("gym.Models.Session", "Session")
                        .WithMany("Reviews")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008484");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("gym.Models.Schedule", b =>
                {
                    b.HasOne("gym.Models.Session", "Session")
                        .WithMany("Schedules")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008472");

                    b.HasOne("gym.Models.Userr", "Trainer")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainerId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008471");

                    b.Navigation("Session");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("gym.Models.Session", b =>
                {
                    b.HasOne("gym.Models.Userr", "Member")
                        .WithMany("SessionMembers")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008462");

                    b.HasOne("gym.Models.Userr", "Trainer")
                        .WithMany("SessionTrainers")
                        .HasForeignKey("TrainerId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008463");

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("gym.Models.Subscription", b =>
                {
                    b.HasOne("gym.Models.MembershipPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008454");

                    b.HasOne("gym.Models.Userr", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008453");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gym.Models.Testimonial", b =>
                {
                    b.HasOne("gym.Models.Userr", "User")
                        .WithMany("Testimonials")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008489");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gym.Models.UserLogin", b =>
                {
                    b.HasOne("gym.Models.Userr", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .HasConstraintName("SYS_C008499");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gym.Models.Userr", b =>
                {
                    b.HasOne("gym.Models.Rolee", "Role")
                        .WithMany("Userrs")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008440");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("gym.Models.WorkoutPlan", b =>
                {
                    b.HasOne("gym.Models.Userr", "Member")
                        .WithMany("WorkoutPlanMembers")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008478");

                    b.HasOne("gym.Models.Userr", "Trainer")
                        .WithMany("WorkoutPlanTrainers")
                        .HasForeignKey("TrainerId")
                        .IsRequired()
                        .HasConstraintName("SYS_C008477");

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("gym.Models.MembershipPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("gym.Models.Rolee", b =>
                {
                    b.Navigation("Userrs");
                });

            modelBuilder.Entity("gym.Models.Session", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("gym.Models.Subscription", b =>
                {
                    b.Navigation("SubscriptionWorkouts");
                });

            modelBuilder.Entity("gym.Models.Userr", b =>
                {
                    b.Navigation("Aboutuspages");

                    b.Navigation("Contactuspages");

                    b.Navigation("Homepages");

                    b.Navigation("Schedules");

                    b.Navigation("SessionMembers");

                    b.Navigation("SessionTrainers");

                    b.Navigation("Subscriptions");

                    b.Navigation("Testimonials");

                    b.Navigation("UserLogins");

                    b.Navigation("WorkoutPlanMembers");

                    b.Navigation("WorkoutPlanTrainers");
                });

            modelBuilder.Entity("gym.Models.WorkoutPlan", b =>
                {
                    b.Navigation("SubscriptionWorkouts");
                });
#pragma warning restore 612, 618
        }
    }
}
